// Built-in fun topics for Extempore mode. Add, remove or edit freely.
export const BUILT_IN_TOPICS = [
  "Friendship",
  "My most embarrassing moment",
  "If animals could talk, the first thing they'd say",
  "The worst advice I've ever received",
  "A world without the internet",
  "Pizza: overrated or underrated?",
  "My villain origin story",
  "The perfect day off",
  "A superpower I'd secretly hate",
  "Why cats secretly rule the world",
  "The weirdest thing I've ever Googled",
  "If I became a billionaire tomorrow",
  "A conspiracy theory I'd start",
  "My dream road trip",
  "The best excuse for being late",
  "Something everyone pretends to like",
  "What I'd put in a time capsule",
  "My go-to karaoke song and why",
  "The most useless talent I have",
  "Monday mornings",
  "If I could swap lives with anyone for a day",
  "A rule I'd make if I were in charge of the world",
  "The dumbest thing I believed as a kid",
  "How I'd survive a zombie apocalypse",
  "A hill I will die on",
  "The best snack combo ever",
  "If my pet wrote a diary about me",
  "A movie that deserves a sequel",
  "The worst gift I've ever received",
  "My biggest fear (the funny kind)",
  "Procrastination",
  "What aliens would think of humans",
  "A hidden talent nobody knows I have",
  "Why school should start at noon",
  "The ultimate sleepover",
  "If I had a personal theme song",
  "A day in the life of my future self",
  "The worst haircut in history",
  "What I'd do with one hour of invisibility",
  "Why breakfast is the best meal",
  "Teamwork",
  "Midnight snacks",
  "If I opened a restaurant",
  "The most overrated holiday",
  "A place I'd love to visit",
];
